
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package GymEnterprise;

/**
 *
 * @author Soham Chavan
 */

import GymEnterprise.ManageMembers;
import GymEnterprise.GymMembership;
import GymEnterprise.model.GymAdmin;
import GymEnterprise.model.GymEmployee;
import com.mysql.cj.xdevapi.Statement;
import main.signUp; // Import the SignUp class
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import university.Model.Student;
import university.student;
import university.Model.Professor;
import university.professor;

public class GymEnterpriseLogin extends javax.swing.JFrame {

    /**
     * Creates new form InventoryEnterpriseLogin
     */
    public GymEnterpriseLogin() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        labelRole = new javax.swing.JLabel();
        cfRole = new javax.swing.JComboBox<>();
        buttonLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GYM ENTERPRISE LOGIN ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        labelUsername.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        labelUsername.setText("USERNAME: ");
        jPanel1.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        labelPassword.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        labelPassword.setText("PASSWORD: ");
        jPanel1.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 80, -1));
        jPanel1.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 200, -1));

        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 200, -1));

        labelRole.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        labelRole.setText("ROLE:");
        jPanel1.add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 74, -1));

        cfRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee", "Gym Member" }));
        jPanel1.add(cfRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 90, -1));

        buttonLogin.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pfPasswordActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonLoginActionPerformed

        String username = tfUsername.getText().trim();
        String password = new String(pfPassword.getPassword()).trim();
        String role = cfRole.getSelectedItem().toString();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter both Username and Password!");
            return;
        }

        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root",
                    "user@1234");
            PreparedStatement preparedStatement;
            ResultSet resultSet;

            switch (role) {
                case "Admin":
                    // Hardcoded admin credentials
                    if (username.equals("admin") && password.equals("admin")) {
                        JOptionPane.showMessageDialog(null, "Admin Login Successful!");
                        this.setVisible(false);
                        GymAdmin admin = new GymAdmin("admin", "admin", "admin");
                        new ManageMembers(admin).setVisible(true); // Redirect to ManageMembers for Admin
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Admin Credentials!");
                    }
                    break;

                case "Employee":
                    // Check employee table
                    preparedStatement = connection.prepareStatement(
                            "SELECT * FROM universitysystem.gym_employee WHERE username = ? AND password = ?");
                    preparedStatement.setString(1, username);
                    preparedStatement.setString(2, password);
                    resultSet = preparedStatement.executeQuery();

                    if (resultSet.next()) {
                        String employeeId = resultSet.getString("employeeId");
                        String name = resultSet.getString("name");

                        String empUsername = resultSet.getString("username");
                        String empPassword = resultSet.getString("password");

                        GymEmployee employee = new GymEmployee(employeeId, name, role, empUsername, empPassword);
                        JOptionPane.showMessageDialog(null, "Employee Login Successful!");
                        this.setVisible(false);
                        new GymMembership().setVisible(true); // Pass the GymEmployee object
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Employee Credentials!");
                    }
                    break;

                case "Gym Member":
                    // Check students, professors, and gym_members tables for members
                    preparedStatement = connection.prepareStatement(
                            "SELECT * FROM universitysystem.students WHERE username = ? AND password = ? " +
                                    "UNION SELECT * FROM universitysystem.professors WHERE username = ? AND password = ? "
                                    +
                                    "UNION SELECT * FROM universitysystem.gym_members WHERE username = ? AND password = ?");
                    preparedStatement.setString(1, username);
                    preparedStatement.setString(2, password);
                    preparedStatement.setString(3, username);
                    preparedStatement.setString(4, password);
                    preparedStatement.setString(5, username);
                    preparedStatement.setString(6, password);
                    resultSet = preparedStatement.executeQuery();

                    if (resultSet.next()) {
                        JOptionPane.showMessageDialog(null, "Gym Member Login Successful!");
                        this.setVisible(false);
                        new GymMembership().setVisible(true); // Redirect to GymMembership for Members
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Gym Member Credentials!");
                    }
                    break;

                default:
                    JOptionPane.showMessageDialog(null, "Invalid Role Selection!");
                    break;
            }

            // connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

    }// GEN-LAST:event_buttonLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        signUp signUpObj = new signUp();
        setVisible(false);
        signUpObj.setVisible(true);

    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GymEnterpriseLogin.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GymEnterpriseLogin.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GymEnterpriseLogin.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GymEnterpriseLogin.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GymEnterpriseLogin().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JComboBox<String> cfRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}