/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GymEnterprise;

import GymEnterprise.ManageMembers;
import GymEnterprise.GymEnterpriseLogin;
import GymEnterprise.model.GymEmployee;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author suhas
 */
public class GymMembership extends javax.swing.JFrame {
     private GymEmployee loggedInEmployee;
    /**
     * Creates new form crimeAction
     */
    public GymMembership() {
        
        initComponents();
        setResizable(false);
        displayEmployeeDetails();
    }
private void displayEmployeeDetails() {
        if (loggedInEmployee != null) {
            JOptionPane.showMessageDialog(this, "Welcome, " + loggedInEmployee.getName() + " (" + loggedInEmployee.getRole() + ")");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnViewMembers = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAddMember = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ManageGymMembership = new javax.swing.JLabel();
        txtMemberName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnStudLogout = new javax.swing.JButton();
        txtCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Phone:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 200, 100, 20);

        btnViewMembers.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnViewMembers.setText("View Record");
        btnViewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMembersActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewMembers);
        btnViewMembers.setBounds(389, 402, 108, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Address:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 240, 58, 20);

        btnAddMember.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnAddMember.setText("Submit");
        btnAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemberActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddMember);
        btnAddMember.setBounds(687, 402, 73, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Membership Status:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 280, 160, 20);

        ManageGymMembership.setBackground(new java.awt.Color(0, 0, 0));
        ManageGymMembership.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        ManageGymMembership.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageGymMembership.setText("Membership Status");
        jPanel1.add(ManageGymMembership);
        ManageGymMembership.setBounds(350, 90, 240, 26);

        txtMemberName.setEnabled(false);
        jPanel1.add(txtMemberName);
        txtMemberName.setBounds(687, 158, 189, 22);

        txtPhone.setEnabled(false);
        jPanel1.add(txtPhone);
        txtPhone.setBounds(687, 199, 189, 22);

        txtAddress.setEnabled(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress);
        txtAddress.setBounds(687, 240, 189, 22);

        memberTable.setForeground(new java.awt.Color(153, 0, 0));
        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "Address", "Membership Status"
            }
        ));
        memberTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(memberTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 150, 452, 226);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 160, 70, 20);

        btnStudLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnStudLogout.setText("Logout");
        btnStudLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudLogout);
        btnStudLogout.setBounds(800, 20, 74, 25);

        txtCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        jPanel1.add(txtCombo);
        txtCombo.setBounds(690, 280, 190, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMembersActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel)memberTable.getModel();
    model.setRowCount(0);
    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user@1234");
         Statement statement = connection.createStatement();
         ResultSet rs = statement.executeQuery("SELECT * FROM universitysystem.gym_members")) {
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("name"),
                rs.getString("phone"),
                rs.getString("address"),
                rs.getString("membership_status")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnViewMembersActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void memberTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberTableMouseClicked
        // TODO add your handling code here:
   DefaultTableModel memberModel = (DefaultTableModel) memberTable.getModel();
String selectedName = memberTable.getValueAt(memberTable.getSelectedRow(), 0).toString();

// Set values to the text fields
txtMemberName.setText(selectedName);
txtAddress.setText(memberTable.getValueAt(memberTable.getSelectedRow(), 1).toString());
txtPhone.setText(memberTable.getValueAt(memberTable.getSelectedRow(), 3).toString());
txtCombo.setSelectedItem(memberTable.getValueAt(memberTable.getSelectedRow(), 2).toString());

System.out.println(selectedName);

try {
    // Establish database connection
    Connection connection = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/universitysystem", "root", "user@1234"
    );

    // Use a prepared statement to prevent SQL injection
    String memberQuery = "SELECT * FROM universitysystem.gym_members WHERE name = ?";
    PreparedStatement preparedStatement = connection.prepareStatement(memberQuery);
    preparedStatement.setString(1, selectedName);

    ResultSet memberData = preparedStatement.executeQuery();

    while (memberData.next()) {
        String memberUsername = memberData.getString("username");
        System.out.println(memberUsername);
    }

    // Close resources
    preparedStatement.close();
    connection.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
        


    }//GEN-LAST:event_memberTableMouseClicked


    private void btnStudLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudLogoutActionPerformed
        // TODO add your handling code here:
     int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
    
    if (response == JOptionPane.YES_OPTION) {
        // Close the current window
        this.setVisible(false);
        this.dispose();

        // Redirect to the GymEnterpriseLogin page
        new GymEnterpriseLogin().setVisible(true);
    }
    }//GEN-LAST:event_btnStudLogoutActionPerformed

    private void btnAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMemberActionPerformed
        // TODO add your handling code here:

      
    DefaultTableModel model = (DefaultTableModel) memberTable.getModel();
    model.setRowCount(0);
    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user@1234");
         Statement statement = connection.createStatement();
         ResultSet rs = statement.executeQuery("SELECT * FROM gym_members")) {
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("name"),
                rs.getString("phone"),
                rs.getString("address"),
                rs.getString("membership_status")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {
                                        
    // Retrieve input values from text fields
    String name = txtMemberName.getText().trim();
    String phone = txtPhone.getText().trim();
    String address = txtAddress.getText().trim();
    String membershipStatus = txtCombo.getSelectedItem().toString();

    // Input validation
    if (name.isEmpty() || phone.isEmpty() || address.isEmpty() || membershipStatus.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please Enter All Details!");
        return;
    }

    try {
        // Parse phone number to ensure it's a valid integer
        int phoneNumber = Integer.parseInt(phone);

        // Establish database connection
        Connection connection = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/universitysystem", "root", "user@1234");

        // Prepare the SQL insert statement
        String insertQuery = "INSERT INTO universitysystem.gym_members (name, phone, address, membership_status) VALUES (?, ?, ?, ?)";
        PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
        preparedStatement.setString(1, name);
        preparedStatement.setInt(2, phoneNumber);
        preparedStatement.setString(3, address);
        preparedStatement.setString(4, membershipStatus);

        // Execute the insert statement
        int rowsInserted = preparedStatement.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Member Added Successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to Add Member!");
        }

        // Close the prepared statement and connection
        preparedStatement.close();
        connection.close();

        // Optionally, clear the fields after adding the member
        txtMemberName.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtCombo.setSelectedIndex(0);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid Phone Number!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }


}

private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {
   
GymEnterpriseLogin gymLoginObj = new GymEnterpriseLogin();
        setVisible(false);
        gymLoginObj.setVisible(true);
        //
    }//GEN-LAST:event_btnAddMemberActionPerformed



    /**
     * @param args the command line arguments
     */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GymMembership().setVisible(true);
            }
        });
}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManageGymMembership;
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnStudLogout;
    private javax.swing.JButton btnViewMembers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable memberTable;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JComboBox<String> txtCombo;
    private javax.swing.JTextField txtMemberName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
